### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by MaxKingPor** [ZihanType/rudi#3]
* To better handle Errors during instantiation, use `try_resolve_xxx` or `try_get_xxx` to get the instance

**Comment by ZihanType** [comment]
`Rudi` is by design just a place to construct instances automatically, and when it has finished constructing instances at the beginning of a program, it is no longer needed. For following code to work correctly, errors should be thrown as early as possible, so I purposely didn't add APIs that return `Result<_, _>` types, just some APIs that return `Option<_>`. Have you encountered any scenarios where you had to manually deal with `Result<_, _>`, please let me know!
